import { useRecoilState, useSetRecoilState } from 'recoil';
import nextId from '@/common/itemid';

import { useCallback } from 'react';
import { itemList, selectedId } from './atom';
import { TListItem } from '@/common/types';

// to add/update resources in the list, we have to take care of a multiple things including
// id, selection, order, etc. This custom hook makes this process as resuable function.
export default function useUpdateItems() {
  const [items, setItems] = useRecoilState(itemList);
  const setSelectedId = useSetRecoilState(selectedId);

  // omit the id since the process of adding doesn't need to know the ID. ID will be automatically generated by the database.
  const addItem = useCallback(
    (newItem: Omit<TListItem, 'id'>) => {
      // get next id
      const curId = nextId();
      const itemWithId = { ...newItem, id: curId };
      let len = 0;

      let success = true;

      setItems((prev) => {
        len = prev.length;

        if (prev.find((pv) => pv.src === newItem.src)) {
          success = false;
          return prev;
        }

        return [itemWithId, ...prev];
      });

      if (len === 0) {
        setSelectedId(curId);
      }

      return success;
    },
    [items],
  );

  return { addItem };
}
